import {cardProfile,analyzeDeckContext,themeFacetForLabel} from "../lab3/deck-context.mjs";
import {COVERAGE} from "../semantic-v2/schema.mjs";
import {DECK_QUALITY_VERSION} from "./schema.mjs";
const clamp01=x=>Math.max(0,Math.min(1,Number(x)||0));const round=(x,d=4)=>Number((Number(x)||0).toFixed(d));
const accessibleFaces=c=>(c?.faces||[]).filter(f=>["default","alternative_entry"].includes(f.access?.kind||"default"));
const isLand=c=>Boolean(c?.views?.mana?.isPlayableLand??accessibleFaces(c).some(f=>(f.cardTypes||[]).includes("Land")));
const manaValue=c=>{const a=c?.views?.castability?.entries||[];const vals=(a.length?a:accessibleFaces(c)).map(x=>Number(x.manaValue)).filter(Number.isFinite);return vals.length?Math.min(...vals):0;};
const role=(p,k)=>{const r=p.roleScores||{};if(k==="resources")return Math.max(r.card_draw||0,(r.tutor||0)*.85,(r.card_selection||0)*.5);if(k==="interaction")return Math.max(r.removal||0,r.counterspell||0,(r.graveyard_hate||0)*.65);if(k==="wipes")return r.board_wipe||0;if(k==="resilience")return Math.max(r.protection||0,r.recursion||0);if(k==="finishers")return r.finisher||0;return r[k]||0;};
function structural(profiles){const targets={ramp:10,resources:10,interaction:10,wipes:2,resilience:5,finishers:2},scores={};for(const [k,t] of Object.entries(targets)){const got=profiles.reduce((n,p)=>n+role(p,k),0);scores[k]=clamp01(got/t);}return {score:Object.values(scores).reduce((a,b)=>a+b,0)/Object.keys(scores).length,components:scores};}
function mana(profiles,commander){const colors=commander?.colorIdentity||[];if(!colors.length)return {score:1,sources:{}};const counts=Object.fromEntries(colors.map(c=>[c,0]));for(const p of profiles){const card=p.card;if(!isLand(card)&&Number(p.roleScores?.mana_source||0)<.45)continue;for(const src of card?.views?.mana?.sources||[]){let cs=[...(src.colors||[])];if(src.anyColor||src.commanderIdentity||src.chosenColor)cs=[...colors];const reliability=(src.coverage===COVERAGE.PARTIAL?.74:src.coverage===COVERAGE.GAP?.35:1)*(src.requiresOtherPermanent?.65:1)*(src.sacrifice?.75:1);for(const c of cs)if(c in counts)counts[c]+=reliability;}for(const face of accessibleFaces(card)){const sub=new Set(face.subtypes||[]),map={Plains:"W",Island:"U",Swamp:"B",Mountain:"R",Forest:"G"};for(const [st,c] of Object.entries(map))if(sub.has(st)&&c in counts)counts[c]=Math.max(counts[c],counts[c]+.85);}}
  const score=colors.reduce((n,c)=>n+clamp01(Number(counts[c]||0)/10),0)/colors.length;return {score,sources:Object.fromEntries(Object.entries(counts).map(([k,v])=>[k,round(v,2)]))};}
function curve(profiles){const nonlands=profiles.filter(p=>!isLand(p.card)),avg=nonlands.length?nonlands.reduce((n,p)=>n+manaValue(p.card),0)/nonlands.length:0;return {score:clamp01(1-Math.abs(avg-3.15)/4),averageManaValue:round(avg,2)};}
function diversity(profiles){const facets=new Set(),types=new Set();for(const p of profiles){const primary=p.semantic?.theme?.summary?.primary;if(primary)facets.add(primary);for(const t of p.types||[])types.add(t);}return {score:clamp01((facets.size/8)*.7+(types.size/6)*.3),themeFacets:facets.size,cardTypes:types.size};}
export function evaluateDeckQuality({engine="unknown",cards=[],commander=null,theme="",themeModel=null}={}){const resolved=(cards||[]).filter(Boolean),profiles=resolved.filter(c=>c.name!==commander?.name).map(card=>cardProfile(card,{theme,themeModel,themeMode:themeModel?.mode||"semantic",commander})),context=analyzeDeckContext(profiles,{commander,theme}),struct=structural(profiles),manaResult=mana(profiles,commander),curveResult=curve(profiles),div=diversity(profiles),supported=profiles.filter(p=>p.card.status===COVERAGE.SUPPORTED).length,partial=profiles.filter(p=>p.card.status===COVERAGE.PARTIAL).length,gap=profiles.filter(p=>p.card.status===COVERAGE.GAP).length,semantic=profiles.length?(supported+partial*.65)/profiles.length:0,mapped=themeFacetForLabel(theme,commander),themeEvaluable=Boolean(mapped?.facet||mapped?.kind==="neutral"||themeModel?.trusted),themeFidelity=themeEvaluable?(mapped?.kind==="neutral"?1:profiles.length?profiles.reduce((n,p)=>n+Number(p.semanticTheme||0),0)/profiles.length:0):null,metrics={themeFidelity:themeFidelity==null?null:clamp01(themeFidelity),structuralCoverage:clamp01(struct.score),manaReliability:clamp01(manaResult.score),dependencySatisfaction:clamp01(context.summary.avgDependencySatisfaction),deadCardSafety:clamp01(1-context.summary.avgDeadCardRisk),curve:clamp01(curveResult.score),semanticCoverage:clamp01(semantic),diversity:clamp01(div.score)},baseWeights={themeFidelity:.20,structuralCoverage:.20,manaReliability:.16,dependencySatisfaction:.14,deadCardSafety:.10,curve:.08,semanticCoverage:.07,diversity:.05};let den=0,num=0;for(const [k,w] of Object.entries(baseWeights)){if(metrics[k]==null)continue;den+=w;num+=metrics[k]*w;}const score=den?num/den:0;return {version:DECK_QUALITY_VERSION,engine,score:round(score),metrics:Object.fromEntries(Object.entries(metrics).map(([k,v])=>[k,v==null?null:round(v)])),weights:Object.fromEntries(Object.entries(baseWeights).filter(([k])=>metrics[k]!=null).map(([k,w])=>[k,round(w/den)])),evaluable:{themeFidelity:themeEvaluable},diagnostics:{resolvedCards:resolved.length,profileCards:profiles.length,coverage:{supported,partial,gap},structural:struct.components,manaSources:manaResult.sources,averageManaValue:curveResult.averageManaValue,dependencyCoverage:round(context.summary.dependencyCoverage),dependencyRedundancy:round(context.summary.dependencyRedundancy),themeFacets:div.themeFacets}};}
export function compareDeckQuality(lab2,vnext){const delta=round(Number(vnext?.score||0)-Number(lab2?.score||0));const components={};for(const k of new Set([...Object.keys(lab2?.metrics||{}),...Object.keys(vnext?.metrics||{})])){const a=lab2?.metrics?.[k],b=vnext?.metrics?.[k];components[k]=(a==null||b==null)?null:round(Number(b)-Number(a));}const severe=delta<-.12||Object.values(components).some(x=>x!=null&&x<-.25);return {delta,noWorse:delta>=-.015,severeRegression:severe,components};}
