// Bilingual UI layer, ported from the original vanilla-JS app. Spanish remains the source
// copy used throughout the app; English is applied only to known UI strings/labels via a
// lookup dictionary plus a handful of regex rules for dynamic (parameterized) strings.
// Card names, deck names and arbitrary user content are never translated.
export const UI_EN = {
  "Historial": "History", "HERRAMIENTA COMMANDER BASADA EN TU COLECCIÓN": "COLLECTION-AWARE COMMANDER TOOL", "Colección pública": "Public collection", "Colección privada": "Private collection", "COLECCIÓN PRIVADA": "PRIVATE COLLECTION", "COLECCIÓN PÚBLICA": "PUBLIC COLLECTION",
  "LEER COLECCIÓN PÚBLICA": "READ PUBLIC COLLECTION", "Abrir colección →": "Open collection →", "No hace falta iniciar sesión si la colección es pública.": "You don't need to sign in for a public collection.",
  "Caché": "Cache", "Actualizar / Borrar": "Refresh / Delete", "Cambiar colección": "Switch collection", "Cerrar sesión": "Sign out",
  "Mazos": "Decks", "gestionados": "managed", "Cartas únicas": "Unique cards", "nombres de carta": "card names", "Copias": "Copies", "copias en total": "total copies", "Registros Archidekt": "Archidekt records", "filas informadas": "reported rows",
  "Sincronizando mazos": "Syncing decks", "Preparando…": "Preparing…", "Preparando cache…": "Preparing cache…", "Uso en mazos listo": "Deck usage ready", "Sincronización parcial": "Partial sync", "Carga incompleta": "Incomplete load", "Mazos cargados": "Decks loaded", "Recuperando mazos": "Recovering decks", "Ver errores": "View errors", "Reintentar": "Retry", "Recargar mazos": "Reload decks", "↻ Recargar mazos": "↻ Reload decks", "Recargando mazos": "Reloading decks", "Comprobando carga de mazos…": "Checking deck load…", "Ahora:": "Now:",
  "Explorar Commander": "Explore Commander", "Cualquier leyenda": "Any legendary creature", "Mejorar mi mazo": "Improve my deck", "Deck existente": "Existing deck", "¿Qué Commander puedo armar?": "What Commander can I build?", "Uno específico o toda tu colección": "One specific commander or your whole collection", "Desde tu colección": "From your collection", "Deck check on steroids": "Deck check on steroids", "Deck builder on steroids": "Deck builder on steroids", "Deck check++": "Deck check++", "Deck builder++": "Deck builder++", "Experimental": "Experimental",
  "EXPLORAR COMMANDER": "EXPLORE COMMANDER", "Buscá una criatura legendaria y cruzá EDHREC con tu colección.": "Search for a legendary creature and cross-reference EDHREC with your collection.", "Analizar colección →": "Analyze collection →",
  "MEJORAR MI MAZO": "IMPROVE MY DECK", "DECK SELECCIONADO": "SELECTED DECK", "Analizar mazo →": "Analyze deck →", "Exportar decklist ⇩": "Export decklist ⇩", "Abrir en Archidekt ↗": "Open in Archidekt ↗", "Identificando Commander…": "Identifying Commander…", "Leyendo detalle exacto del mazo…": "Reading exact deck details…", "Compará cada propuesta IN/OUT por función, curva y redundancia antes de aplicarla al mazo.": "Compare each IN/OUT proposal by function, curve and redundancy before applying it to the deck.", "Revisá cada cambio según tu plan de juego, presupuesto y metajuego antes de aplicarlo.": "Review each change against your game plan, budget and metagame before applying it.",
  "Chequeo del mazo": "Deck Check", "SALUD DEL MAZO + SALUD DE TEMÁTICAS": "DECK HEALTH + THEME HEALTH", "SOLO LAB": "LAB ONLY", "Solo LAB": "LAB only", "SALUD DEL MAZO · EXPERIMENTAL": "DECK HEALTH · EXPERIMENTAL", "EDHREComendaciones": "EDHREC Recommendations", "Ordenar": "Sort", "Ordenar…": "Sort…", "Tipo": "Type", "Categoría": "Category", "Nombre": "Name", "Tipo ↑": "Type ↑", "Tipo ↓": "Type ↓", "Categoría ↑": "Category ↑", "Categoría ↓": "Category ↓", "Nombre ↑": "Name ↑", "Nombre ↓": "Name ↓",
  "Cómo leerlo": "How to read it", "Confianza": "Confidence", "Alta": "High", "Media": "Medium", "Baja": "Low",
  "Métricas principales": "Core metrics", "Estructura y balance": "Structure & balance", "Experimental / heurística": "Experimental / heuristic", "Cobertura de interacción": "Interaction coverage", "Roles frágiles": "Fragile roles", "Simulación de desarrollo": "Development simulation",
  "Turno": "Turn", "Mana": "Mana", "Productivo": "Productive", "Engine": "Engine", "Payoff": "Payoff", "Threat": "Threat", "Commander": "Commander", "Carta": "Card", "Primario": "Primary", "Roles": "Roles", "Dependencias": "Dependencies", "Synergy tags": "Synergy tags", "Func.": "Func.", "Conf.": "Conf.",
  "Clasificación semántica": "Semantic classification", "Detalles experimentales": "Experimental details", "Sin datos.": "No data.", "Sin alertas": "No alerts",
  "Resumen del mazo": "Deck overview", "Identidad del mazo": "Deck identity", "Cambios sugeridos · IN/OUT": "Suggested IN/OUT", "No encuentro un corte claro.": "No clear cut found.",
  "Limpiar filtro": "Clear filter", "DECK LIST": "DECK LIST", "SIZE": "SIZE", "cartas": "cards",
  "Actualizar todo ahora": "Refresh everything now", "Borrar todo": "Delete everything", "Caché local": "Local cache", "Actualizar": "Refresh", "Borrar": "Delete", "Todo": "Everything",
  "Vaciar": "Clear", "Agregar al deck actual": "Add to current deck", "Quitar": "Remove", "Exportar TXT": "Export TXT",
  "RESULTADOS": "RESULTS", "Completar a 100": "Complete to 100", "Exportar resultados": "Export results", "TODAS": "ALL", "Todas": "All", "En Colección": "In Collection", "Disponibles": "Available", "Ya en el mazo": "Already in deck", "ORDENAR POR": "SORT BY", "Sinergia": "Synergy", "Inclusión": "Inclusion",
  "SECCIONES EDHREC": "EDHREC SECTIONS", "CARTA": "CARD", "TIPO": "TYPE", "CATEGORÍA": "CATEGORY", "COLECCIÓN": "COLLECTION",
  "Tu colección.": "Your collection.", "Tu próximo deck.": "Your next deck.",
  "↑ más alto = mejor": "↑ higher = better", "↓ más bajo = mejor": "↓ lower = better", "◎ mejor cerca de 1.0": "◎ best near 1.0", "◌ lectura contextual": "◌ contextual reading", "↓ más temprano = mejor": "↓ earlier = better", "◌ no es score": "◌ not a score",
  "colores correctos en T3": "correct colors by T3", "turnos productivos en T3": "productive turns by T3", "densidad de recursos": "resource density", "densidad de interacción": "interaction density", "densidad de payoffs": "payoff density", "densidad de engines": "engine density", "roles ponderados por carta": "weighted roles per card", "setup por payoff": "setup per payoff", "consistencia estimada": "estimated consistency", "densidad de sinergia": "synergy density", "dependencia del commander": "commander dependency", "función sin commander": "function without commander", "mana value efectivo": "effective mana value", "riesgo estructural": "structural risk", "hito ≥50%": "≥50% milestone", "capacidad de cierre": "closing ability", "simulaciones": "simulations",
  "Cartas": "Cards", "Acceso T5": "T5 access", "Disponible T5": "Available T5", "Fuerte": "Strong", "Moderada": "Moderate", "Redundancia": "Redundancy", "Sin graveyard": "Without graveyard", "Sin artifacts": "Without artifacts", "Reducers": "Reducers", "Señaladas": "Flagged", "Finishers": "Finishers", "Extra combats": "Extra combats", "Avg mulligans": "Avg mulligans",
  "Todos usan una señal principal comparable y debajo muestran las variables que la explican. Tocá una tarjeta para ver exactamente qué cartas participan.": "Each metric uses a primary signal with the variables that explain it underneath. Click a card to see exactly which deck cards contribute.",
  "Cómo está construido el mazo: redundancia, roles, dependencia, resiliencia y curva real.": "How the deck is built: redundancy, roles, dependency, resilience and real curve.",
  "Señales útiles pero más dependientes de interpretación; permanecen plegadas para reducir ruido.": "Useful signals that depend more on interpretation; kept collapsed to reduce noise.",
  "Cada bloque es clickeable y la cantidad coincide con la deck list filtrada.": "Each block is clickable and its count matches the filtered deck list.",
  "No detecté roles sostenidos por una sola carta.": "No roles supported by a single card were detected.",
  "No encontré un rol crítico sostenido por una sola pieza.": "No critical role supported by a single piece was found.",
  "Lectura de T1–T7 · pasá por la i de cada columna para ver su definición.": "T1–T7 view · hover the info icon on each column for its definition.",
  "Estas métricas son experimentales y se muestran sólo en LAB. No alteran EDHREComendaciones ni los cambios IN/OUT.": "These metrics are validated here. They do not modify EDHREC Recommendations or IN/OUT.",
  "La cifra grande concentra el foco; los datos secundarios explican de dónde sale.": "The large number carries the focus; secondary data explains where it comes from.",
  "Leyendo Commander, Size y cartas del deck…": "Reading Commander, Size and deck cards…", "Analizando recomendaciones, estructura, curva e identidad…": "Analyzing recommendations, structure, curve and identity…",
  "DESCUBRIR COMMANDERS": "DISCOVER COMMANDERS", "Explorá únicamente criaturas legendarias Commander-legales de tu colección. EDHREC se consulta solo cuando elegís analizar o comparar.": "Explore only Commander-legal legendary creatures from your collection. EDHREC is queried only when you choose to analyze or compare.",
  "FILTRAR POR TAG EDHREC": "FILTER BY EDHREC TAG", "Elegí uno o varios. No hace falta recorrer toda la lista.": "Choose one or more. You don't need to browse the whole list.", "Ver todos los tags": "Show all tags", "COMMANDERS DE TU COLECCIÓN": "COMMANDERS FROM YOUR COLLECTION", "Cargando Commanders de tu colección…": "Loading Commanders from your collection…", "Ocultar Commanders": "Hide Commanders",
  "COMPARAR SELECCIÓN · HASTA 10": "COMPARE SELECTION · UP TO 10", "Elegí entre 2 y 10 criaturas legendarias de tu colección. ManaShelf consulta EDHREC solamente para esas cartas y las ordena por cantidad de recomendaciones que ya tenés.": "Choose 2 to 10 legendary creatures from your collection. ManaShelf queries EDHREC only for those cards and ranks them by how many recommendations you already own.", "Comparar selección": "Compare selection", "Analizando…": "Analyzing…", "progreso de red no cuantificable": "network progress cannot be quantified",
  "⚗ MANASHELF LAB": "⚗ MANASHELF LAB", "FUNCIÓN EXPERIMENTAL · SOLO LECTURA · NO MODIFICA ARCHIDEKT": "EXPERIMENTAL FEATURE · READ ONLY · DOES NOT MODIFY ARCHIDEKT", "DECK HEALTH + THEME HEALTH": "DECK HEALTH + THEME HEALTH", "Analizá un mazo con métricas experimentales sin modificar tu lista en Archidekt.": "Analyze a deck with experimental metrics without modifying your Archidekt list.", "Analizar Deck Health →": "Analyze Deck Health →", "Clasificando cartas y detectando el plan del mazo…": "Classifying cards and detecting the deck plan…",
  "RECOMENDACIONES EDHREC ÚNICAS": "UNIQUE EDHREC RECOMMENDATIONS", "EN COLECCIÓN": "IN COLLECTION", "CON COPIA DISPONIBLE": "WITH AN AVAILABLE COPY", "SIN COPIA DISPONIBLE": "WITHOUT AN AVAILABLE COPY", "NO POSEÍDAS": "NOT OWNED", "ROL MANASHELF": "MANASHELF ROLE", "Todos los roles ManaShelf": "All ManaShelf roles", "TEMÁTICA": "THEME", "Todas las temáticas": "All themes", "Estas categorías vienen de EDHREC. Los roles del filtro de arriba los infiere ManaShelf.": "These categories come from EDHREC. ManaShelf infers the roles shown in the filter above.", "No hay cartas para mostrar con estos filtros.": "No cards match these filters.", "Mazos que no pudieron sincronizarse": "Decks that could not be synced", "Cerrar": "Close", "de las recomendadas que tenés aparecen en al menos un mazo. Ese dato puede superponerse con “disponible” si poseés más de una copia.": "of the recommended cards you own appear in at least one deck. This can overlap with ‘available’ if you own more than one copy.",
  "Resumen": "Summary", "Salud": "Health", "Estructura": "Structure", "Reglas": "Rules", "Identidad": "Identity", "Métricas": "Metrics", "Motor de métricas del mazo": "Deck Metrics Engine",
  "Fiabilidad de maná": "Mana Reliability", "Desarrollo temprano": "Early Development", "Flujo de recursos": "Resource Flow", "Interacción": "Interaction", "Amenazas / Payoffs": "Threats / Payoffs", "Densidad de engines": "Engine Density", "Densidad funcional": "Functional Density", "Consistencia": "Consistency", "Densidad de sinergia": "Synergy Density", "Dependencia": "Dependency", "Resiliencia": "Resilience", "MV efectivo": "Effective MV", "Riesgo de carta muerta": "Dead-card Risk", "Turno de relevancia": "Turn of Relevance", "Capacidad de cierre": "Closing Power",
  "Proxy de cartas muertas": "Dead-card proxy", "Evidencia de cierre": "Closing evidence", "Resumen de resiliencia": "Resilience snapshot", "Tocar para ampliar Commander": "Click to enlarge Commander",
  "Mazo": "Deck", "Sin errores.": "No errors.", "NO ESTÁ EN TU COLECCIÓN": "NOT IN YOUR COLLECTION", "Sin categoría": "Uncategorized",
  "Seleccioná un mazo primero.": "Select a deck first.", "No pude identificar el Commander del mazo.": "I couldn't identify the deck's Commander.", "Conectá una colección primero.": "Connect a collection first.",
  "Consultando recomendaciones EDHREC…": "Fetching EDHREC recommendations…", "Cruzando recomendaciones con tu colección…": "Cross-referencing recommendations with your collection…", "Calculando copias disponibles y uso en otros mazos…": "Calculating available copies and use in other decks…", "Preparando recomendaciones y disponibilidad…": "Preparing recommendations and availability…",
  "Analizando tu mazo…": "Analyzing your deck…", "Analizando Commander…": "Analyzing Commander…", "Las cartas más usadas.": "Most-used cards.", "Clasificación publicada por EDHREC.": "Ranking published by EDHREC.", "No está en tu colección": "Not in your collection",
  "Uso de cartas": "Card usage", "No hay cartas poseídas en la shortlist.": "There are no owned cards in the shortlist.", "Sinergia EDHREC alta, sin un rol prioritario pendiente": "High EDHREC synergy with no priority role still missing",
  "de tu colección para explorar": "from your collection to explore", "Mostrar menos": "Show less", "Podés seleccionar hasta 10 Commanders.": "You can select up to 10 Commanders.", "Preparando Commanders de tu colección…": "Preparing Commanders from your collection…", "Reintentando con carga directa…": "Retrying with direct loading…", "No pude cargar Commanders.": "I couldn't load Commanders.", "Cruzando con tu colección…": "Cross-referencing with your collection…",
  "La contraseña se envía al bridge de autenticación configurado para obtener una sesión de Archidekt; ManaShelf no la guarda en su caché local.": "The password is sent to the configured authentication bridge to obtain an Archidekt session; ManaShelf does not store it in its local cache.", "Borrar texto": "Clear text", "Tocá la carta para ampliarla": "Click the card to enlarge", "Commander por identificar": "Commander not identified yet", "Commander aún no identificado": "Commander not identified yet", "Cargando Commander…": "Loading Commander…",
  "Plan de combo": "Combo plan", "No buscar combos": "Do not search for combos", "Sólo si encaja": "Only if it fits", "Priorizar combo infinito": "Prioritize infinite combo", "Usa Commander Spellbook. Si elige un paquete, LAB 3 bloquea todas sus piezas exactas o ninguna.": "Uses Commander Spellbook. If LAB 3 chooses a package, it locks every exact piece or none.",
  "LAB 1": "LAB 1", "Deck Health + Themes": "Deck Health + Themes", "Deck Builder · Colección": "Deck Builder · Collection", "LAB 2": "LAB 2", "Deck Builder": "Deck Builder", "⚗2 MANASHELF LAB 2": "⚗2 MANASHELF LAB 2", "GENERADOR EXPERIMENTAL · CONSTRUYE DESDE TU COLECCIÓN · NO MODIFICA ARCHIDEKT": "EXPERIMENTAL BUILDER · BUILDS FROM YOUR COLLECTION · DOES NOT MODIFY ARCHIDEKT",
  "BUILD FROM COLLECTION": "BUILD FROM COLLECTION", "Elegí un Commander, una mecánica y dejá que ManaShelf arme el mejor mazo coherente posible con las cartas disponibles.": "Choose a Commander and a mechanic, then let ManaShelf build the strongest coherent deck it can from the cards available.",
  "Buscá una criatura legendaria Commander-legal.": "Search for a Commander-legal legendary creature.", "La construcción prioriza esta mecánica sin sacrificar estructura, curva ni maná.": "The build prioritizes this mechanic without sacrificing structure, curve, or mana.", "Ajustes": "Settings", "Definen prioridades del armado. El motor sigue respetando legalidad, estructura y validación de maná.": "These settings define build priorities. The engine still respects legality, structure, and mana validation.",
  "Foco en el theme": "Theme focus", "Cuánto espacio priorizar para cartas que realmente expresan el theme elegido.": "How much space to prioritize for cards that genuinely express the selected theme.", "Ramp": "Ramp", "Cuánta aceleración de maná buscar, además del ajuste automático por curva y coste del Commander.": "How much mana acceleration to seek, in addition to automatic adjustments for curve and Commander cost.", "Cuánto espacio dedicar a removal, counters, wipes y otras respuestas.": "How much space to devote to removal, counters, wipes, and other answers.", "Curva": "Curve", "Cuánto favorecer costes bajos y penalizar cartas caras al ordenar candidatos.": "How strongly to favor lower costs and penalize expensive cards when ranking candidates.",
  "Sinergia vs eficiencia": "Synergy vs efficiency", "Balancea piezas que trabajan con el plan contra cartas fuertes y eficientes por sí solas.": "Balances pieces that advance the plan against cards that are individually strong and efficient.", "Dependencia del Commander": "Commander dependency", "Cuánto aceptar cartas cuyo rendimiento baja si el Commander no está disponible.": "How much to accept cards whose performance drops when the Commander is unavailable.", "Es independiente del theme. Usa Commander Spellbook y, si elige un combo, incluye todas sus piezas exactas o ninguna.": "Independent of the theme. Uses Commander Spellbook and, when a combo is selected, includes every exact piece or none of them.", "Sin buscar combos": "Do not seek combos", "Combos sinérgicos": "Synergistic combos", "Base de maná": "Mana base", "Define cuánto priorizar básicas o fixing. Siempre se validan colores producidos, pips, curva y ramp; “Básicas primero” sólo conserva no básicas realmente importantes.": "Controls how strongly to prioritize basics versus fixing. Produced colors, pips, curve, and ramp are always validated; ‘Basics first’ keeps only genuinely important nonbasics.", "Proteger mazos existentes": "Protect existing decks", "No usa copias que ya están comprometidas en otros mazos cuando la sincronización puede verificarlo.": "Avoids copies already committed to other decks when synchronization can verify their use.",
  "Estándar": "Standard", "Más": "More", "Alto": "High", "Más interacción": "More interaction", "Más ramp": "More ramp", "Mucho ramp": "Heavy ramp", "Más respuestas": "More answers", "Normal": "Normal", "Más baja": "Lower", "Lo más rápida coherente": "Fastest coherent", "Muy baja": "Very low", "Sinergia primero": "Synergy first", "Balanceado": "Balanced", "Eficiencia primero": "Efficiency first", "Conservador": "Conservative", "All-in": "All-in", "Baja dependencia": "Low dependency", "Alta dependencia": "High dependency", "Básicas primero": "Basics first", "Segura": "Safe", "Segura · más tierras": "Safe · more lands", "Balanceada": "Balanced", "Lean": "Lean", "Ajustada · menos tierras": "Lean · fewer lands",
  "Generar mazo →": "Build deck →", "Elegí un theme para continuar.": "Choose a theme to continue.", "Preparando pool legal de tu colección…": "Preparing the legal pool from your collection…", "MAZO GENERADO · LAB 2": "GENERATED DECK · LAB 2", "Regenerar": "Rebuild", "Deck list · roles y categorías": "Deck list · roles and categories", "La categoría indica por qué la carta ocupa ese slot principal; una carta puede cubrir varios roles.": "The category explains why the card occupies its primary slot; one card may cover multiple roles.", "DISPONIBILIDAD": "AVAILABILITY",
  "Auditoría del mazo generado": "Generated deck audit", "Se vuelve a evaluar el resultado con el mismo Deck Health y Deck Metrics experimentales del LAB.": "The result is evaluated again with the same experimental Deck Health and Deck Metrics used in LAB.", "Fallback balanceado": "Balanced fallback", "Inferido del Commander": "Inferred from Commander", "Lista completa": "Complete list", "Colección insuficiente": "Insufficient collection", "TIERRAS": "LANDS", "ESTRUCTURA": "STRUCTURE", "COPIAS": "COPIES", "ramp / interacción": "ramp / interaction", "ramp fiable / interacción": "reliable ramp / interaction", "Compromisos detectados": "Trade-offs detected", "Notas del armado": "Build notes", "Nota": "Note",
  "Commander poseído": "Commander owned", "Commander no poseído": "Commander not owned", "En colección": "In collection", "Criterio de armado": "Build criteria", "objetivos, maná y decisiones": "targets, mana, and decisions", "Objetivos dinámicos": "Dynamic targets", "Recursos": "Resources", "Protección / recursión": "Protection / recursion", "Sin demanda de color detectada.": "No color demand detected.", "Filtrando cartas legales por identidad de color…": "Filtering legal cards by color identity…", "Cargando Oracle text y roles desde Scryfall…": "Loading Oracle text and roles from Scryfall…", "Buscando combos completos en Commander Spellbook…": "Searching Commander Spellbook for complete combos…", "Midiendo afinidad con el Commander y el theme…": "Measuring affinity with the Commander and theme…", "Cubriendo ramp, recursos, interacción y resiliencia…": "Covering ramp, resources, interaction, and resilience…", "Calculando curva y base de maná…": "Calculating curve and mana base…", "Auditando el resultado con Deck Health…": "Auditing the result with Deck Health…", "Exportar para Archidekt ⇩": "Export for Archidekt ⇩", "Copiar para Archidekt": "Copy for Archidekt", "Exportar log diagnóstico": "Export diagnostic log", "Copiado ✓": "Copied ✓", "Básica ilimitada": "Unlimited basic", "Generá un mazo primero.": "Build a deck first.", "No hay un log de armado disponible.": "No build log is available.", "No pude copiar el decklist al portapapeles.": "I couldn't copy the decklist to the clipboard.", "Balance por tipo": "Type balance", "Combo seleccionado": "Selected combo", "Combo infinito": "Infinite combo", "Combo completo": "Complete combo", "Resultado": "Result", "Maná requerido": "Mana required", "básicas": "basics", "no básicas": "nonbasics", "fetches": "fetches", "3 tierras en T3": "3 lands by T3",
  "Semantic builder": "Semantic builder", "⚗3 MANASHELF LAB 3": "⚗3 MANASHELF LAB 3", "SEMANTIC BUILDER · CONTRATOS + CONTEXTO DE DECK · LAB 2 PERMANECE INTACTO": "SEMANTIC BUILDER · CONTRACTS + DECK CONTEXT · LAB 2 REMAINS UNCHANGED",
  "Debe existir en el índice semántico y ser Commander-legal.": "Must exist in the semantic index and be Commander-legal.", "El contrato semántico decide compatibilidad; EDHREC puede ordenar, no fabricar afinidad.": "The semantic contract decides compatibility; EDHREC may rank candidates, not manufacture affinity.", "Prioridades del builder contextual. No usa Classification 7 para decidir el deck.": "Contextual builder priorities. It does not use Classification 7 to choose the deck.",
  "Prioridad de densidad temática semántica.": "Priority for semantic theme density.", "Aceleración estructural, no simples mana abilities.": "Structural acceleration, not ordinary mana abilities.", "Removal, counters y graveyard hate con dirección semántica.": "Removal, counters, and graveyard hate with semantic directionality.", "Preferencia por costes bajos sin ignorar el contexto.": "Preference for lower costs without ignoring context.", "Balance entre contratos/contexto y señales externas.": "Balance between contracts/context and external signals.", "Penaliza cartas cuyo plan necesita al Commander disponible.": "Penalizes cards whose plan requires the Commander to be available.", "Básicas ilimitadas; no básicas desde tu colección.": "Unlimited basics; nonbasics come from your collection.", "No toma copias comprometidas cuando el uso cruzado está sincronizado.": "Avoids committed copies when cross-deck usage is synchronized.",
  "Generar con LAB 3 →": "Build with LAB 3 →", "Preparando Semantic DB…": "Preparing Semantic DB…", "MAZO GENERADO · LAB 3": "GENERATED DECK · LAB 3", "Exportar log semántico": "Export semantic log", "Contexto semántico": "Semantic context", "dependencias, coverage y bottlenecks": "dependencies, coverage, and bottlenecks", "Selección contextual LAB 3": "LAB 3 contextual selection", "El status semántico expone cuándo una carta todavía depende de cobertura parcial.": "Semantic status shows when a card still depends on partial coverage.", "DECK HEALTH · COMPARACIÓN": "DECK HEALTH · COMPARISON", "Evalúa el resultado de LAB 3 con la misma interfaz de Deck Health y Deck Metrics de LAB 2 para poder compararlos. Esta auditoría ocurre después del build y no interviene en la selección semántica.": "Evaluates the LAB 3 result with the same Deck Health and Deck Metrics interface as LAB 2 for direct comparison. This audit runs after the build and does not influence semantic selection.", "Facetas del theme": "Theme facets", "Fuentes restringidas": "Restricted sources", "Sin fuentes restringidas seleccionadas.": "No restricted sources selected.",
  "Inferido por Semantic DB": "Inferred by Semantic DB", "Fallback estructural": "Structural fallback", "Contrato semántico": "Semantic contract", "Fallback EDHREC": "EDHREC fallback", "Theme EDHREC sin contrato especializado; LAB 3 usa la página temática como evidencia externa y mantiene legalidad, roles, dependencias y maná semánticos.": "EDHREC theme without a specialized contract; LAB 3 uses the theme page as external evidence while keeping semantic legality, roles, dependencies, and mana checks.", "No encontré themes para este Commander.": "No themes found for this Commander.", "Consultando Semantic DB + themes…": "Querying Semantic DB + themes…", "Validando Commander en Semantic DB…": "Validating Commander in Semantic DB…", "Lista incompleta": "Incomplete list", "contratos semánticos": "semantic contracts", "SEMÁNTICA": "SEMANTICS", "MANÁ": "MANA", "DEPENDENCIAS": "DEPENDENCIES", "PACKAGES": "PACKAGES", "Coverage estructural": "Structural coverage", "Fuentes de maná": "Mana sources", "Contexto de packages": "Package context", "Sin roles detectados.": "No roles detected.", "No hay bottlenecks fuertes detectados.": "No strong bottlenecks detected.", "fuentes de color cubiertas": "color sources covered", "Producer → consumer links": "Producer → consumer links", "Dependency coverage": "Dependency coverage",
  "LAB 3 · ACCESO EXPERIMENTAL": "LAB 3 · EXPERIMENTAL ACCESS", "Semantic Builder Lab": "Semantic Builder Lab", "LAB 3 usa la misma clave experimental de LAB 2.": "LAB 3 uses the same experimental password as LAB 2.", "Entrar a LAB 3": "Enter LAB 3", "El log de LAB 3 ya no está disponible. Regenerá el mazo.": "The LAB 3 log is no longer available. Rebuild the deck.", "Ese Commander no está en el índice semántico de LAB 3.": "That Commander is not in the LAB 3 semantic index.", "LAB 3 todavía no tiene cobertura semántica suficiente para ese Commander.": "LAB 3 does not yet have sufficient semantic coverage for that Commander.", "Elegí un theme válido para LAB 3.": "Choose a valid LAB 3 theme.", "No hay log LAB 3 disponible.": "No LAB 3 log is available.",
  "LAB 3 · STRESS HARNESS v3": "LAB 3 · STRESS HARNESS v3", "Corpus automático · 200 builds": "Automatic corpus · 200 builds", "Selecciona Commanders y themes de forma estratificada sobre el pool global Commander-legal del runtime semántico, registra semántica directa, inferida o fallback efectivo, ejecuta LAB 3 y agrupa anomalías por familia. El stress es deliberadamente independiente de tu colección y no modifica LAB 2 ni tus mazos.": "Selects Commanders and themes with stratified sampling from the global Commander-legal semantic runtime pool, mixes semantic contracts and EDHREC fallback, runs LAB 3, and clusters anomalies by family. Stress is intentionally independent of your collection and does not modify LAB 2 or your decks.", "Ejecutar 200 builds": "Run 200 builds", "Detener": "Stop", "Exportar corpus ZIP": "Export corpus ZIP", "Listo para ejecutar.": "Ready to run.",
};

export const UI_ATTR_EN = {
  "usuario de Archidekt": "Archidekt username", "contraseña": "password", "Buscar criatura legendaria…": "Search legendary creature…", "Escribí el nombre del mazo…": "Type the deck name…", "Buscar mazo para analizar…": "Search deck to analyze…",
  "Cambiar entre tema oscuro y claro": "Switch between dark and light theme", "Cambiar tema": "Change theme", "Cambiar idioma": "Change language", "Ocultar/mostrar la lista del mazo": "Hide/show deck list", "Ordenar deck": "Sort deck", "Ordenar deck del LAB": "Sort LAB deck", "Información": "Information", "Abrir deck list": "Open deck list", "Ocultar deck list": "Hide deck list", "Tocar para ampliar Commander": "Click to enlarge Commander", "Vista grande del Commander": "Large Commander preview", "Ordenar deck generado": "Sort generated deck",
};

// Dynamic (parameterized) strings that a plain dictionary lookup cannot cover.
const DYNAMIC_RULES = [
  [/^Theme seleccionado · (.+)$/, (m) => `Selected theme · ${m[1]}`],
  [/^(\d+) decks EDHREC$/, (m) => `${m[1]} EDHREC decks`],
  [/^(\d+) decks EDHREC · Fallback EDHREC$/, (m) => `${m[1]} EDHREC decks · EDHREC fallback`],
  [/^(\d+) decks EDHREC · Contrato semántico$/, (m) => `${m[1]} EDHREC decks · Semantic contract`],
  [/^objetivo (\d+)$/, (m) => `target ${m[1]}`],
  [/^(\d+) color(?:es)? bajo objetivo$/, (m) => `${m[1]} color source${Number(m[1]) === 1 ? "" : "s"} below target`],
  [/^Maná ([WUBRGC])$/, (m) => `Mana ${m[1]}`],
  [/^([0-9.,]+) \/ ([0-9.,]+) fuentes$/, (m) => `${m[1]} / ${m[2]} sources`],
  [/^([WUBRGC]) · demanda (\d+) pips$/, (m) => `${m[1]} · demand ${m[2]} pips`],
  [/^Carga incompleta · (\d+)\/(\d+)$/, (m) => `Incomplete load · ${m[1]}/${m[2]}`],
  [/^Recuperando mazos · (\d+)\/(\d+)$/, (m) => `Recovering decks · ${m[1]}/${m[2]}`],
  [/^Recargando mazos · (\d+)\/(\d+)$/, (m) => `Reloading decks · ${m[1]}/${m[2]}`],
  [/^Cargando mazos · (\d+)\/(\d+)$/, (m) => `Loading decks · ${m[1]}/${m[2]}`],
  [/^(\d+) mazo(?:s)? no (?:pudo|pudieron) cargarse después de los reintentos automáticos\.$/, (m) => `${m[1]} deck${Number(m[1]) === 1 ? "" : "s"} could not be loaded after automatic retries.`],
  [/^Reintento automático (\d+)\/(\d+)…$/, (m) => `Automatic retry ${m[1]}/${m[2]}…`],
  [/^Reintento (\d+)\/(\d+) · (.+)$/, (m) => `Retry ${m[1]}/${m[2]} · ${m[3]}`],
  [/^(\d+) desde caché · (\d+) actualizados · carga completa$/, (m) => `${m[1]} from cache · ${m[2]} refreshed · complete load`],
  [/^Commander · (.+)$/, (m) => `Commander · ${m[1]}`],
  [/^Size · (\d+) cartas$/, (m) => `Size · ${m[1]} cards`],
  [/^Filtro: (.+) · (\d+) cartas$/, (m) => `Filter: ${m[1]} · ${m[2]} cards`],
  [/^(\d+) criterios evaluados$/, (m) => `${m[1]} criteria evaluated`],
  [/^Criterio · (.+)$/, (m) => `Criterion · ${m[1]}`],
  [/^(\d+) cartas$/, (m) => `${m[1]} cards`],
  [/^EN TU COLECCIÓN · (\d+) copia(?:s)?$/, (m) => `IN YOUR COLLECTION · ${m[1]} cop${Number(m[1]) === 1 ? "y" : "ies"}`],
  [/^Disponible · (\d+)$/, (m) => `Available · ${m[1]}`],
  [/^En otros mazos · (\d+)$/, (m) => `In other decks · ${m[1]}`],
  [/^objetivo (\d+) · MV (.+)$/, (m) => `target ${m[1]} · MV ${m[2]}`],
  [/^(\d+) cartas · objetivo (\d+)$/, (m) => `${m[1]} cards · target ${m[2]}`],
  [/^(\d+) slots con copia disponible · (\d+) ocupados$/, (m) => `${m[1]} slots with an available copy · ${m[2]} occupied`],
  [/^(\d+) candidatos legales evaluados · builder v(.+) · (.+)$/, (m) => `${m[1]} legal candidates evaluated · builder v${m[2]} · ${m[3]}`],
  [/^Objetivo inicial (\d+) → final (\d+)\. (.+)\.$/, (m) => `Initial target ${m[1]} → final ${m[2]}. ${m[3]}.`],
  [/^(\d+)% demanda$/, (m) => `${m[1]}% demand`],
  ["COMMANDER NO POSEÍDO · el 99 se arma desde tu colección", () => "COMMANDER NOT OWNED · the 99 is built from your collection"],
];

export function translate(text) {
  if (!text) return text;
  if (UI_EN[text]) return UI_EN[text];
  for (const [pattern, fn] of DYNAMIC_RULES) {
    if (typeof pattern === "string") {
      if (text === pattern) return fn();
      continue;
    }
    const m = text.match(pattern);
    if (m) return fn(m);
  }
  return text;
}

export function translateAttr(text) {
  if (!text) return text;
  return UI_ATTR_EN[text] || translate(text);
}
