import fs from "node:fs/promises";
import path from "node:path";
import {fileURLToPath} from "node:url";
import {buildKnowledgeDb} from "./knowledge-db.mjs";
import {ThemeCorpusCatalog} from "./theme-corpus-catalog.mjs";
import {KnowledgeCatalog} from "./knowledge-catalog.mjs";
import {createThemeCorpus,auditThemeCorpus} from "./theme-corpus.mjs";
import {auditThemeCorpusSweep} from "./theme-corpus-sweep-audit.mjs";
import {installThemeCorpusCandidate} from "./theme-corpus-install.mjs";
import {createThemeEvidenceArtifact,assertThemeEvidenceArtifact} from "./theme-evidence.mjs";
import {createThemeEvidencePlan} from "./theme-evidence-plan.mjs";
import {fetchEdhrecTrainingSnapshot} from "./theme-evidence-fetch.mjs";
import {writeJsonAtomic,writeJsonGzipAtomic,readJsonMaybeGzip,sha256File} from "./io.mjs";
import {Lab3RuntimeCatalog} from "../lab3/runtime-catalog.mjs";
import {LAB3_BUILDER_VERSION,LAB3_MANA_MODEL_VERSION} from "../lab3/builder.mjs";
import {LAB3_CONTEXT_ENGINE_VERSION} from "../lab3/deck-context.mjs";
import {LAB3_THEME_UNDERSTANDING_VERSION} from "../lab3/theme-understanding.mjs";
import {benchmarkPair} from "./quality-benchmark.mjs";
import {evaluatePromotionGate} from "./promotion-gate.mjs";

const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,"../..");
const args=process.argv.slice(2),cmd=args.shift()||"status";
const opt=name=>{const i=args.indexOf(`--${name}`);return i>=0?args[i+1]:null;};
const runtimePath=path.join(root,"data/lab3-runtime-index.jsonl.gz"),themePath=path.join(root,"data/lab3-theme-corpus.json.gz"),knowledgePath=path.join(root,"data/lab3-knowledge-db.json");
const knowledgeMetadata=()=>({builderBoundary:"vnext-candidate",builderVersion:LAB3_BUILDER_VERSION,themeUnderstandingVersion:LAB3_THEME_UNDERSTANDING_VERSION,contextEngineVersion:LAB3_CONTEXT_ENGINE_VERSION,manaModelVersion:LAB3_MANA_MODEL_VERSION,status:"candidate"});
async function build(){const db=await buildKnowledgeDb({runtimePath,themeCorpusPath:themePath,outputPath:knowledgePath,metadata:knowledgeMetadata()});console.log(JSON.stringify(db,null,2));}
async function status(){const theme=new ThemeCorpusCatalog({projectRoot:root}),knowledge=new KnowledgeCatalog({projectRoot:root});console.log(JSON.stringify({themeCorpus:await theme.status(),knowledge:await knowledge.status()},null,2));}
async function evidencePlan(){const output=path.resolve(opt("output")||path.join(root,"data/lab3-theme-evidence-plan.json")),count=Math.max(1,Number(opt("count")||300)),seed=opt("seed")||"manashelf-theme-evidence-plan-v1",excludeRaw=String(opt("exclude")||"").split(/[;,]/).map(x=>x.trim()).filter(Boolean),excluded=new Set();for(const file of excludeRaw){const raw=JSON.parse(await fs.readFile(path.resolve(file),"utf8")),rows=Array.isArray(raw)?raw:(raw.commanders||raw.cases||[]);for(const row of rows){const id=row.commanderOracleId||row.oracleId;if(id)excluded.add(String(id));}}const catalog=new Lab3RuntimeCatalog({projectRoot:root}),idx=await catalog.ensureLoaded(),plan=createThemeEvidencePlan({runtimeCards:[...idx.byOracleId.values()],runtimeSha256:await sha256File(runtimePath),seed,count,excludeOracleIds:excluded});await writeJsonAtomic(output,plan);console.log(JSON.stringify({output,fingerprint:plan.fingerprint,summary:plan.summary},null,2));}
async function evidenceFetch(){const planFile=opt("plan"),output=path.resolve(opt("output")||path.join(root,"data/lab3-edhrec-training-snapshot.json"));if(!planFile)throw new Error("knowledge:evidence-fetch requires --plan plan.json");const plan=JSON.parse(await fs.readFile(path.resolve(planFile),"utf8"));let resume=null;try{resume=JSON.parse(await fs.readFile(output,"utf8"));}catch{}const checkpoint=async snap=>writeJsonAtomic(output,snap),progress=async e=>{if(e?.message)console.log(e.message);},snapshot=await fetchEdhrecTrainingSnapshot({plan,themesPerCommander:Math.max(1,Number(opt("themes-per-commander")||6)),minThemeDecks:Math.max(1,Number(opt("min-theme-decks")||5)),requestDelayMs:Math.max(0,Number(opt("delay-ms")||300)),retries:Math.max(0,Number(opt("retries")||2)),requestTimeoutMs:Math.max(1000,Number(opt("timeout-ms")||12000)),resume,onCheckpoint:checkpoint,onProgress:progress});await writeJsonAtomic(output,snapshot);console.log(JSON.stringify({output,fingerprint:snapshot.fingerprint,summary:snapshot.summary,failures:snapshot.failures.slice(-20)},null,2));}
async function evidence(){const input=opt("input");if(!input)throw new Error("knowledge:evidence requires --input snapshot.json");const raw=JSON.parse(await fs.readFile(path.resolve(input),"utf8")),catalog=new Lab3RuntimeCatalog({projectRoot:root}),idx=await catalog.ensureLoaded(),runtimeSha256=await sha256File(runtimePath),artifact=createThemeEvidenceArtifact({samples:raw.samples||[],resolveCard:name=>idx.get(name),runtimeSha256,seed:raw.seed||"manashelf-theme-evidence-v2",source:raw.source||{},provenance:raw.provenance||{},qualityPolicy:{minThemeDecksPerSample:Math.max(1,Number(opt("min-theme-decks")||raw?.source?.minThemeDecks||5))}}),output=path.resolve(opt("output")||path.join(root,"data/lab3-theme-evidence.json"));await writeJsonAtomic(output,artifact);console.log(JSON.stringify({output,summary:artifact.summary,fingerprint:artifact.fingerprint,source:artifact.source},null,2));}
async function themes(){const input=opt("input");if(!input)throw new Error("knowledge:themes requires --input evidence.json");const raw=assertThemeEvidenceArtifact(JSON.parse(await fs.readFile(path.resolve(input),"utf8"))),runtimeSha256=await sha256File(runtimePath);if(raw.runtimeSha256!==runtimeSha256)throw new Error(`Theme Evidence runtime SHA mismatch: expected ${runtimeSha256}, got ${raw.runtimeSha256}`);const catalog=new Lab3RuntimeCatalog({projectRoot:root}),idx=await catalog.ensureLoaded(),themeEvidence={};for(const [theme,rows] of Object.entries(raw.themes||{})){themeEvidence[theme]=(rows||[]).map(r=>{const semanticCard=idx.getByOracleId(r.oracleId)||idx.get(r.name);return semanticCard?{...r,semanticCard}:null;}).filter(Boolean);}const corpus=createThemeCorpus({themeEvidence,themeStats:raw.themeStats||{},runtimeSha256,seed:raw.seed||"manashelf-theme-corpus-v1",provenance:{...raw.provenance,evidenceFingerprint:raw.fingerprint,evidenceSource:raw.source,evidenceQualityPolicy:raw.qualityPolicy||null}}),output=path.resolve(opt("output")||themePath),audit=auditThemeCorpus(corpus),report=opt("report");await writeJsonGzipAtomic(output,corpus);if(report)await fs.writeFile(path.resolve(report),JSON.stringify({schema:"manashelf-theme-corpus-admission-report",schemaVersion:1,createdAt:new Date().toISOString(),input:path.resolve(input),evidenceFingerprint:raw.fingerprint,output,audit},null,2));console.log(JSON.stringify({output,summary:corpus.summary,fingerprint:corpus.fingerprint,evidenceFingerprint:raw.fingerprint,audit:{totalProfiles:audit.totalProfiles,trustedProfiles:audit.trustedProfiles,rejectedProfiles:audit.rejectedProfiles,trustRate:audit.trustRate,rejectionReasons:audit.rejectionReasons},report:report?path.resolve(report):null},null,2));}

async function auditThemes(){const corpusFile=opt("corpus");if(!corpusFile)throw new Error("knowledge:audit-themes requires --corpus candidate-theme-corpus.json.gz");const output=path.resolve(opt("output")||path.join(root,"data/lab3-theme-corpus-audit.json")),sweepOut=opt("sweep"),corpus=await readJsonMaybeGzip(path.resolve(corpusFile)),catalog=new Lab3RuntimeCatalog({projectRoot:root}),idx=await catalog.ensureLoaded(),runtimeSha256=await sha256File(runtimePath),{report,sweep}=auditThemeCorpusSweep({corpus,runtimeCards:[...idx.byOracleId.values()],runtimeSha256,minScore:Number(opt("min-score")||.18),maxThemesPerCard:Math.max(1,Number(opt("max-themes-per-card")||8))});await writeJsonAtomic(output,report);if(sweepOut)await writeJsonGzipAtomic(path.resolve(sweepOut),{schema:"manashelf-theme-corpus-sweep",schemaVersion:1,createdAt:new Date().toISOString(),corpusFingerprint:corpus.fingerprint||null,runtimeSha256,sweepFingerprint:report.sweepFingerprint,rows:sweep});console.log(JSON.stringify({output,decision:report.decision,summary:report.summary,sweepFingerprint:report.sweepFingerprint,sweep:sweepOut?path.resolve(sweepOut):null},null,2));if(args.includes("--require-pass")&&report.decision!=="PASS")process.exitCode=2;}
async function installThemes(){const corpusFile=opt("corpus"),auditFile=opt("audit");if(!corpusFile||!auditFile)throw new Error("knowledge:install-themes requires --corpus candidate.json.gz --audit audit.json");const receipt=await installThemeCorpusCandidate({candidatePath:path.resolve(corpusFile),auditPath:path.resolve(auditFile),runtimePath,targetThemePath:themePath,knowledgePath,receiptPath:opt("receipt")?path.resolve(opt("receipt")):null,metadata:knowledgeMetadata()});console.log(JSON.stringify(receipt,null,2));}
async function quality(){const input=opt("input");if(!input)throw new Error("quality:benchmark requires --input pair.json");const raw=JSON.parse(await fs.readFile(path.resolve(input),"utf8")),catalog=new Lab3RuntimeCatalog({projectRoot:root}),commander=await catalog.get(raw.commander),resolve=async rows=>{const out=[];for(const row of rows||[]){const card=await catalog.get(row.name||row);if(!card)continue;const q=Math.max(1,Number(row.quantity||1));for(let i=0;i<q;i++)out.push(card);}return out;};const report=benchmarkPair({lab2Cards:await resolve(raw.lab2),vnextCards:await resolve(raw.vnext),commander,theme:raw.theme,themeModel:raw.themeModel||null});console.log(JSON.stringify(report,null,2));}
async function promotion(){const input=opt("input");if(!input)throw new Error("promotion:gate requires --input evidence.json");const raw=JSON.parse(await fs.readFile(path.resolve(input),"utf8"));console.log(JSON.stringify(evaluatePromotionGate(raw),null,2));}
try{if(cmd==="build")await build();else if(cmd==="evidence-plan")await evidencePlan();else if(cmd==="evidence-fetch")await evidenceFetch();else if(cmd==="evidence")await evidence();else if(cmd==="themes")await themes();else if(cmd==="audit-themes")await auditThemes();else if(cmd==="install-themes")await installThemes();else if(cmd==="quality")await quality();else if(cmd==="promotion")await promotion();else await status();}catch(e){console.error(String(e?.stack||e));process.exitCode=1;}
