import {cardProfile,analyzeDeckContext,themeFacetForLabel} from "../lab3/deck-context.mjs";
import {COVERAGE} from "../semantic-v2/schema.mjs";
import {DECK_QUALITY_VERSION} from "./schema.mjs";
import {themeMembershipForProfile} from "../lab3/theme-understanding.mjs";
const clamp01=x=>Math.max(0,Math.min(1,Number(x)||0));const round=(x,d=4)=>Number((Number(x)||0).toFixed(d));
const accessibleFaces=c=>(c?.faces||[]).filter(f=>["default","alternative_entry"].includes(f.access?.kind||"default"));
const isLand=c=>Boolean(c?.views?.mana?.isPlayableLand??accessibleFaces(c).some(f=>(f.cardTypes||[]).includes("Land")));
const manaValue=c=>{const a=c?.views?.castability?.entries||[];const vals=(a.length?a:accessibleFaces(c)).map(x=>Number(x.manaValue)).filter(Number.isFinite);return vals.length?Math.min(...vals):0;};
const role=(p,k)=>{const r=p.roleScores||{};if(k==="resources")return Math.max(r.card_draw||0,(r.tutor||0)*.85,(r.card_selection||0)*.5);if(k==="interaction")return Math.max(r.removal||0,r.counterspell||0,(r.graveyard_hate||0)*.65);if(k==="wipes")return r.board_wipe||0;if(k==="resilience")return Math.max(r.protection||0,r.recursion||0);if(k==="finishers")return r.finisher||0;return r[k]||0;};
function structural(profiles){const targets={ramp:10,resources:10,interaction:10,wipes:2,resilience:5,finishers:2},scores={};for(const [k,t] of Object.entries(targets)){const got=profiles.reduce((n,p)=>n+role(p,k),0);scores[k]=clamp01(got/t);}return {score:Object.values(scores).reduce((a,b)=>a+b,0)/Object.keys(scores).length,components:scores};}
function mana(profiles,commander){const colors=commander?.colorIdentity||[];if(!colors.length)return {score:1,sources:{}};const counts=Object.fromEntries(colors.map(c=>[c,0]));for(const p of profiles){const card=p.card;if(!isLand(card)&&Number(p.roleScores?.mana_source||0)<.45)continue;for(const src of card?.views?.mana?.sources||[]){let cs=[...(src.colors||[])];if(src.anyColor||src.commanderIdentity||src.chosenColor)cs=[...colors];const reliability=(src.coverage===COVERAGE.PARTIAL?.74:src.coverage===COVERAGE.GAP?.35:1)*(src.requiresOtherPermanent?.65:1)*(src.sacrifice?.75:1);for(const c of cs)if(c in counts)counts[c]+=reliability;}for(const face of accessibleFaces(card)){const sub=new Set(face.subtypes||[]),map={Plains:"W",Island:"U",Swamp:"B",Mountain:"R",Forest:"G"};for(const [st,c] of Object.entries(map))if(sub.has(st)&&c in counts)counts[c]=Math.max(counts[c],counts[c]+.85);}}
  const score=colors.reduce((n,c)=>n+clamp01(Number(counts[c]||0)/10),0)/colors.length;return {score,sources:Object.fromEntries(Object.entries(counts).map(([k,v])=>[k,round(v,2)]))};}
function curve(profiles){const nonlands=profiles.filter(p=>!isLand(p.card)),avg=nonlands.length?nonlands.reduce((n,p)=>n+manaValue(p.card),0)/nonlands.length:0;return {score:clamp01(1-Math.abs(avg-3.15)/4),averageManaValue:round(avg,2)};}
function diversity(profiles){const facets=new Set(),types=new Set();for(const p of profiles){const primary=p.semantic?.theme?.summary?.primary;if(primary)facets.add(primary);for(const t of p.types||[])types.add(t);}return {score:clamp01((facets.size/8)*.7+(types.size/6)*.3),themeFacets:facets.size,cardTypes:types.size};}
export function evaluateDeckQuality({engine="unknown",cards=[],commander=null,theme="",themeModel=null,themeTarget=null,externalThemeEvidenceByName=null}={}){
  const resolved=(cards||[]).filter(Boolean),externalEvidence=externalThemeEvidenceByName instanceof Map?externalThemeEvidenceByName:new Map(Object.entries(externalThemeEvidenceByName||{}).map(([name,value])=>[String(name).toLocaleLowerCase("en-US"),Number(value||0)]));
  const profiles=resolved.filter(c=>c.name!==commander?.name).map(card=>cardProfile(card,{theme,themeModel,themeMode:themeModel?.mode||"semantic",commander,external:{themeAffinity:Number(externalEvidence.get(String(card.name||"").toLocaleLowerCase("en-US"))||0)}}));
  const context=analyzeDeckContext(profiles,{commander,theme}),struct=structural(profiles),manaResult=mana(profiles,commander),curveResult=curve(profiles),div=diversity(profiles);
  const supported=profiles.filter(p=>p.card.status===COVERAGE.SUPPORTED).length,partial=profiles.filter(p=>p.card.status===COVERAGE.PARTIAL).length,gap=profiles.filter(p=>p.card.status===COVERAGE.GAP).length,semantic=profiles.length?(supported+partial*.65)/profiles.length:0;
  const mapped=themeFacetForLabel(theme,commander),themeEvaluable=Boolean(mapped?.facet||mapped?.kind==="neutral"||themeModel?.trusted||themeModel?.composite),thematicProfiles=profiles.filter(p=>!isLand(p.card));
  let themeFidelity=null,themeDiagnostics=null;
  if(themeEvaluable){
    if(mapped?.kind==="neutral"){themeFidelity=1;themeDiagnostics={mode:"neutral",coverage:1};}
    else {
      const target=Number(themeTarget)>0?Number(themeTarget):Math.max(1,thematicProfiles.length*.55),membershipRows=thematicProfiles.map(p=>({profile:p,membership:themeMembershipForProfile(p,themeModel)}));
      const members=themeModel?.composite?membershipRows.filter(x=>x.membership.member).map(x=>x.profile):thematicProfiles.filter(p=>Number(p.semanticTheme||0)>=.35);
      // Composite support scores are deliberately conservative and are not on the same
      // scale as a direct facet score. Once a card passes the generic semantic membership
      // gate, coverage is count-based; composition remains the guardrail against collapse.
      const semanticMass=themeModel?.composite?members.length:thematicProfiles.reduce((n,p)=>n+Number(p.semanticTheme||0),0),coverage=clamp01(semanticMass/target);
      let composition=1,anchorAlignment=1,secondaryBreadth=1,familyDistributionAlignment=1,actualAnchorShare=null,targetAnchorShare=null,secondaryFamilyCounts={},secondaryFamilyTargets={};
      if(themeModel?.composite&&themeModel?.directFacet){
        const memberRows=membershipRows.filter(x=>x.membership.member);targetAnchorShare=clamp01(Number(themeModel?.compositionTargets?.anchorTargetShare??themeModel.anchorTargetShare??.5));const anchors=memberRows.filter(x=>x.membership.anchor).length;actualAnchorShare=memberRows.length?anchors/memberRows.length:0;
        const tolerance=.10,deviation=Math.max(0,Math.abs(actualAnchorShare-targetAnchorShare)-tolerance),scale=Math.max(.2,Math.max(targetAnchorShare,1-targetAnchorShare));anchorAlignment=clamp01(1-(deviation/scale)*.8);
        for(const row of memberRows.filter(x=>x.membership.secondary&&x.membership.family)){const family=String(row.membership.family);secondaryFamilyCounts[family]=(secondaryFamilyCounts[family]||0)+1;}
        const explicitTargets=themeModel?.compositionTargets?.secondaryTargets||null,priors=themeModel?.secondaryFamilyPriors||{};
        if(explicitTargets&&Object.keys(explicitTargets).length)secondaryFamilyTargets={...explicitTargets};else {const families=Object.keys(secondaryFamilyCounts),den=families.reduce((n,f)=>n+Number(priors[f]||0),0),mass=Math.max(0,1-targetAnchorShare);for(const family of families)secondaryFamilyTargets[family]=mass*(den?Number(priors[family]||0)/den:1/Math.max(1,families.length));}
        const expectedFamilies=Object.entries(secondaryFamilyTargets).filter(([,share])=>Number(share)>.015).map(([family])=>family),coveredFamilies=expectedFamilies.filter(f=>Number(secondaryFamilyCounts[f]||0)>0);secondaryBreadth=expectedFamilies.length?coveredFamilies.length/expectedFamilies.length:1;
        const actual={__anchor:actualAnchorShare};for(const [family,count] of Object.entries(secondaryFamilyCounts))actual[family]=memberRows.length?count/memberRows.length:0;const expected={__anchor:targetAnchorShare,...secondaryFamilyTargets},keys=new Set([...Object.keys(actual),...Object.keys(expected)]);let l1=0;for(const key of keys)l1+=Math.abs(Number(actual[key]||0)-Number(expected[key]||0));familyDistributionAlignment=clamp01(1-Math.min(1,l1/2));composition=anchorAlignment*.35+familyDistributionAlignment*.50+secondaryBreadth*.15;
      }
      themeFidelity=clamp01(coverage*(themeModel?.composite?.60+.40*composition:1));themeDiagnostics={mode:themeModel?.composite?"composite":"direct_or_inferred",semanticMass:round(semanticMass),target:round(target),coverage:round(coverage),memberCards:members.length,actualAnchorShare:actualAnchorShare==null?null:round(actualAnchorShare),targetAnchorShare:targetAnchorShare==null?null:round(targetAnchorShare),anchorAlignment:round(anchorAlignment),secondaryBreadth:round(secondaryBreadth),familyDistributionAlignment:round(familyDistributionAlignment),secondaryFamilyCounts,secondaryFamilyTargets:Object.fromEntries(Object.entries(secondaryFamilyTargets).map(([k,v])=>[k,round(v)])),composition:round(composition)};
    }
  }
  const metrics={themeFidelity:themeFidelity==null?null:clamp01(themeFidelity),structuralCoverage:clamp01(struct.score),manaReliability:clamp01(manaResult.score),dependencySatisfaction:clamp01(context.summary.avgDependencySatisfaction),deadCardSafety:clamp01(1-context.summary.avgDeadCardRisk),curve:clamp01(curveResult.score),semanticCoverage:clamp01(semantic),diversity:clamp01(div.score)};
  const baseWeights={themeFidelity:.20,structuralCoverage:.20,manaReliability:.16,dependencySatisfaction:.14,deadCardSafety:.10,curve:.08,semanticCoverage:.07,diversity:.05};
  let den=0,num=0;for(const [k,w] of Object.entries(baseWeights)){if(metrics[k]==null)continue;den+=w;num+=metrics[k]*w;}
  const weightedScore=den?num/den:0;
  // An additive average can hide a thematically wrong deck behind perfect mana and
  // structure.  Theme fidelity is therefore a quality guardrail whenever the theme
  // is semantically evaluable; it cannot be compensated away by unrelated metrics.
  const themeGuard=metrics.themeFidelity==null?1:clamp01(.50+.50*metrics.themeFidelity),score=Math.min(weightedScore,themeGuard);
  return {version:DECK_QUALITY_VERSION,engine,score:round(score),metrics:Object.fromEntries(Object.entries(metrics).map(([k,v])=>[k,v==null?null:round(v)])),weights:Object.fromEntries(Object.entries(baseWeights).filter(([k])=>metrics[k]!=null).map(([k,w])=>[k,round(w/den)])),evaluable:{themeFidelity:themeEvaluable},diagnostics:{weightedScore:round(weightedScore),themeGuard:round(themeGuard),themeGuardApplied:metrics.themeFidelity!=null&&themeGuard<weightedScore,resolvedCards:resolved.length,profileCards:profiles.length,coverage:{supported,partial,gap},structural:struct.components,manaSources:manaResult.sources,averageManaValue:curveResult.averageManaValue,dependencyCoverage:round(context.summary.dependencyCoverage),dependencyRedundancy:round(context.summary.dependencyRedundancy),dependentCards:Number(context.summary.dependentCards||0),bottleneckCount:(context.bottlenecks||[]).length,themeFacets:div.themeFacets,theme:themeDiagnostics}};
}
export function compareDeckQuality(lab2,vnext){const delta=round(Number(vnext?.score||0)-Number(lab2?.score||0));const components={};for(const k of new Set([...Object.keys(lab2?.metrics||{}),...Object.keys(vnext?.metrics||{})])){const a=lab2?.metrics?.[k],b=vnext?.metrics?.[k];components[k]=(a==null||b==null)?null:round(Number(b)-Number(a));}const severe=delta<-.12||Object.values(components).some(x=>x!=null&&x<-.25);return {delta,noWorse:delta>=-.015,severeRegression:severe,components};}
